// GAME ACTIONS
export const UPDATE_GAME_SETTINGS = 'UPDATE_GAME_SETTINGS';
export const UPDATE_GAME_SCORE = 'UPDATE_GAME_SCORE';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';

// TILE ACTIONS
export const CLICK_TILE = 'CLICK_TILE';
export const SET_UP_BOARD = 'SET_UP_BOARD';
export const REVEAL_TILE = 'REVEAL_TILE';
// export const FETCH_INSTRUCTIONS_SUCCESS = 'FETCH_INSTRUCTIONS_SUCCESS';
// export const FETCH_INSTRUCTIONS_FAILURE = 'FETCH_INSTRUCTIONS_FAILURE';