// GAME ACTIONS
export const SET_GAME_DIFFICULTY = 'SET_GAME_DIFFICULTY';
export const UPDATE_GAME_SCORE = 'UPDATE_GAME_SCORE';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';

// TILE ACTIONS
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const SET_UP_BOARD = 'SET_UP_BOARD';
export const REVEAL_TILE = 'REVEAL_TILE';
export const REVEAL_EMPTY_TILES = 'REVEAL_EMPTY_TILES';
export const TOGGLE_FLAG = 'TOGGLE_FLAG';

// Leaderboard Actions
export const FETCH_LEADERBOARD_REQUEST = 'FETCH_LEADERBOARD_REQUEST';
export const FETCH_LEADERBOARD_SUCCESS = 'FETCH_LEADERBOARD_SUCCESS';
export const FETCH_LEADERBOARD_FAILURE = 'FETCH_LEADERBOARD_FAILURE,';